# Use the official Redis image as the base image
FROM redis:latest

# Set the working directory to /usr/src/app
WORKDIR /usr/src/app

# Copy the Redis configuration file to the container
COPY redis.conf /usr/src/app/redis.conf

# Expose the Redis port
EXPOSE 6379

# Run Redis with the custom configuration file
CMD ["redis-server", "/usr/src/app/redis.conf"]