# Generated by Django 5.0.4 on 2024-05-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_session_at',
            new_name='last_session',
        ),
    ]
