# Generated by Django 5.0.4 on 2024-05-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_last_session_at_user_last_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='protect_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
