# Use the official NGINX base image
FROM nginx

# Copy custom configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# Copy static files to the container
COPY static /usr/share/nginx/html

# Expose port 80 for HTTP traffic
EXPOSE 80

# Start NGINX server
CMD ["nginx", "-g", "daemon off;"]